import type { SkyParams } from '../types'

export const PRESET_ORDER = [
  'GOLDEN_HOUR',
  'BLUE_HOUR',
  'VOLCANIC',
  'ARCTIC',
  'STORM',
  'AURORA',
] as const

export type PresetName = (typeof PRESET_ORDER)[number]

const baseEffects = {
  noiseEnabled: false,
  noiseOpacity: 0.06,
  noiseScale: 10,
  noiseAnimated: false,
  barsEnabled: false,
  barWidth: 24,
  refractStrength: 60,
  barSeed: 42,
}

export const createDefaultEffects = () => ({ ...baseEffects })

export const PRESETS: Record<PresetName, SkyParams> = {
  GOLDEN_HOUR: {
    zenithHue: 268,
    zenithSaturation: 55,
    zenithLightness: 12,
    horizonHue: 28,
    horizonSaturation: 92,
    horizonLightness: 52,
    horizonIntensity: 0.85,
    hazeWidth: 0.4,
    hazeIntensity: 0.72,
    atmosphericScatter: 0.3,
    sunsetIntensity: 0.9,
    clarity: 0.6,
    groundHue: 20,
    groundSaturation: 22,
    groundLightness: 12,
    radialDispersion: 0,
    gradientScale: 1,
    gradientShift: 0,
    preset: 'GOLDEN_HOUR',
    effects: createDefaultEffects(),
  },
  BLUE_HOUR: {
    zenithHue: 228,
    zenithSaturation: 72,
    zenithLightness: 8,
    horizonHue: 195,
    horizonSaturation: 60,
    horizonLightness: 62,
    horizonIntensity: 0.5,
    hazeWidth: 0.35,
    hazeIntensity: 0.48,
    atmosphericScatter: 0.7,
    sunsetIntensity: 0.1,
    clarity: 0.75,
    groundHue: 220,
    groundSaturation: 14,
    groundLightness: 8,
    radialDispersion: 0.25,
    gradientScale: 1,
    gradientShift: 0,
    preset: 'BLUE_HOUR',
    effects: createDefaultEffects(),
  },
  VOLCANIC: {
    zenithHue: 0,
    zenithSaturation: 0,
    zenithLightness: 4,
    horizonHue: 14,
    horizonSaturation: 98,
    horizonLightness: 38,
    horizonIntensity: 1,
    hazeWidth: 0.55,
    hazeIntensity: 0.62,
    atmosphericScatter: 0.1,
    sunsetIntensity: 1,
    clarity: 0.3,
    groundHue: 8,
    groundSaturation: 18,
    groundLightness: 5,
    radialDispersion: 0.6,
    gradientScale: 1,
    gradientShift: 0,
    preset: 'VOLCANIC',
    effects: createDefaultEffects(),
  },
  ARCTIC: {
    zenithHue: 210,
    zenithSaturation: 40,
    zenithLightness: 72,
    horizonHue: 185,
    horizonSaturation: 28,
    horizonLightness: 88,
    horizonIntensity: 0.2,
    hazeWidth: 0.6,
    hazeIntensity: 0.4,
    atmosphericScatter: 0.5,
    sunsetIntensity: 0,
    clarity: 0.9,
    groundHue: 200,
    groundSaturation: 10,
    groundLightness: 20,
    radialDispersion: 0.1,
    gradientScale: 1,
    gradientShift: 0,
    preset: 'ARCTIC',
    effects: createDefaultEffects(),
  },
  STORM: {
    zenithHue: 248,
    zenithSaturation: 18,
    zenithLightness: 10,
    horizonHue: 58,
    horizonSaturation: 22,
    horizonLightness: 32,
    horizonIntensity: 0.3,
    hazeWidth: 0.7,
    hazeIntensity: 0.34,
    atmosphericScatter: 0.6,
    sunsetIntensity: 0.15,
    clarity: 0.2,
    groundHue: 240,
    groundSaturation: 12,
    groundLightness: 4,
    radialDispersion: 0,
    gradientScale: 1,
    gradientShift: 0,
    preset: 'STORM',
    effects: createDefaultEffects(),
  },
  AURORA: {
    zenithHue: 155,
    zenithSaturation: 80,
    zenithLightness: 18,
    horizonHue: 280,
    horizonSaturation: 85,
    horizonLightness: 22,
    horizonIntensity: 0.65,
    hazeWidth: 0.5,
    hazeIntensity: 0.58,
    atmosphericScatter: 0.4,
    sunsetIntensity: 0.3,
    clarity: 0.85,
    groundHue: 160,
    groundSaturation: 18,
    groundLightness: 6,
    radialDispersion: 0.35,
    gradientScale: 1,
    gradientShift: 0,
    preset: 'AURORA',
    effects: createDefaultEffects(),
  },
}

export const DEFAULT_PRESET: PresetName = 'GOLDEN_HOUR'
